version: "3.7"

services:
    mongo:
        container_name: ferro-mongo
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=foobar
            - MONGO_INITDB_ROOT_PASSWORD=foobar2000
        volumes:
            - /data/db:/data/db

    ferrothorn:
        build:
            context: .
        ports:
            - 80:80
        environment:
            - MONGO_HOST=ferro-mongo
            - MONGO_USER=foobar
            - MONGO_PASS=foobar2000
            - FERRO_LOG_LEVEL=2
            - FERRO_SECRET
        volumes:
            - ~/.ferrothorn/files:/files
