version: "3"

services:
    ferrothorn:
        build:
            context: .
        ports:
            - 80:8000
        environment:
            - FERROTHORN_ROOT=/files
            - FERROTHORN_CONNECTION
            - FERROTHORN_SECRET
        volumes:
            - ./ferrothorn/files:/files
