version: "3.7"

services:
    mongo:
        container_name: ferro-mongo-dev
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=devel
            - MONGO_INITDB_ROOT_PASSWORD=foobar2000
        volumes:
            - ~/.ferrothorn/db:/data/db

    ferrothorn:
        build:
            context: .
        ports:
            - 80:80
        environment:
            - FERRO_MONGO_HOST=ferro-mongo-dev
            - FERRO_MONGO_USER=devel
            - FERRO_MONGO_PASS=foobar2000
            - FERRO_MONGO_BASE=develop
            - FERRO_LOG_LEVEL=2
            - FERRO_SECRET
        volumes:
            - ~/.ferrothorn/files:/files
