version: "3"

services:
    mongo:
        container_name: ferro-mongo
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=ferrothorn
            - MONGO_INITDB_ROOT_PASSWORD=ferrothorn-local
        volumes:
            - /ferrothorn/db:/data/db
    ferrothorn:
        build:
            context: .
        ports:
            - 80:80
        environment:
            - FERRO_MONGO_HOST=ferro-mongo
            - FERRO_MONGO_USER=ferrothorn
            - FERRO_MONGO_PASS=ferrothorn-local
            - FERRO_MONGO_BASE=ferrothorn
            - FERRO_LOG_LEVEL=1
            - FERRO_SECRET
        volumes:
            - /ferrothorn/files:/files
